site/pages/index.tsx

> Supports all possible languages available on the VS Code extension marketplace. That’s over 200 languages. All you need is a .tmlangauge file for anything not shipped with Shiki.
tmlangauge → tmlanguage

Fix typo in first paragraph

---

packages/eleventy-plugin-shiki-twoslash/package.json
pnpm-lock.yaml

Was trying to use the 11ty plugin and the `deasync` dependency used was not listed in its `package.json`. This adds it.

Add missing deasync dependency to 11ty plugin `package.json`

---

packages/twoslash-cli/index.js

Fixes #14
Unlike other packages, [twoslash-cli](https://github.com/shikijs/twoslash/tree/main/packages/twoslash-cli) depends on v3+ of [unist-util-visit](https://www.npmjs.com/package/unist-util-visit), which uses a single export for `visit` instead of a default one.
I have changed the import statement accordingly.

Fix import of visit from unist-util-visit

---

CONTRIBUTING.md
packages/remark-shiki-twoslash/test/fixtures.test.ts
pnpm-lock.yaml

Abuse the Jest module mocking system to make the shiki-twoslash module lookup use the app's source-code instead of the built version.

Use the jest module system to re-write shiki-twoslash to the dev build

---

packages/remark-shiki-twoslash/test/fixtures.test.ts
packages/remark-shiki-twoslash/test/fixtures/accurateErrors.md
packages/remark-shiki-twoslash/test/results/accurateErrors.html
packages/remark-shiki-twoslash/test/results/accurateErrors.json
packages/remark-shiki-twoslash/test/results/codefenceHighlight.html
packages/remark-shiki-twoslash/test/results/exporting.html
packages/remark-shiki-twoslash/test/results/generics.html
packages/remark-shiki-twoslash/test/results/highlight.html
packages/remark-shiki-twoslash/test/results/importNodeTypes.html
packages/remark-shiki-twoslash/test/results/inline-angle-brackets.html
packages/remark-shiki-twoslash/test/results/large-chopped.html
packages/remark-shiki-twoslash/test/results/one.html
packages/remark-shiki-twoslash/test/results/simple-interface.html
packages/remark-shiki-twoslash/test/results/simple.html
packages/remark-shiki-twoslash/test/results/twoliner.html
packages/remark-shiki-twoslash/test/results/usingJSX.html
packages/shiki-twoslash/src/utils.ts

This PR adds an algorithm to nest these tags correctly. It (at least locally) passes all the tests and highlight properly with all the default themes from shiki.
Closes #25

fix: add algorithm for nesting tags

---

packages/docusaurus-preset-shiki-twoslash/package.json
packages/eleventy-plugin-shiki-twoslash/package.json
packages/gatsby-remark-shiki-twoslash/package.json
packages/hexo-shiki-twoslash/package.json
packages/markdown-it-shiki-twoslash/package.json
packages/remark-shiki-twoslash/package.json
packages/remark-shiki-twoslash/src/index.ts
packages/twoslash-cli/package.json
packages/vuepress-plugin-shiki-twoslash/package.json
pnpm-lock.yaml

Re: #35 - I spotted @phryneas used a weak map to solve the issue  https://github.com/phryneas/remark-typescript-tools/commit/53ade28557d270968c339c1e7c7217a646e1abfd 
Maybe that's enough for us too

Use a weakmap for the highlighters

---

examples/docusaurus/docusaurus.config.js
examples/docusaurus/package.json
examples/docusaurus/scripts/clone_docs.mjs
examples/docusaurus/yarn.lock
packages/remark-shiki-twoslash/src/index.ts

fix: cache promises instead of highlighters

---

packages/eleventy-plugin-shiki-twoslash/README.md

Adds note about minimum Eleventy version, link to the relevant issue, and link to the example in the repository for reference. Closes #51.

Add Eleventy minimum version to plugin readme

---

markdown.config.js
package.json
packages/shiki-twoslash/README.md
pnpm-lock.yaml

I built https://github.com/orta/markdown-magic-inline-types to keep these in sync

Ensure all types in the READMEs are up to date

---

package.json
packages/remark-shiki-twoslash/src/index.ts
packages/remark-shiki-twoslash/test/results/jsdocInlineAttributes.html
packages/shiki-twoslash/README.md
packages/shiki-twoslash/src/index.ts
packages/shiki-twoslash/src/renderers/twoslash.ts

The only thing here was that we didn't have a full pipeline for options to go from user input all the way to a renderer and now we do.

JSDoc support

---

.changeset/dull-boats-switch.md
packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/index.js

Hi! 👋🏽 
This PR proposes a fix to a bug found when investigating https://github.com/remotion-dev/remotion/issues/496: the copy button works fine in development but doesn't work in production.
After investigation, I noticed the reason being the "cast" of `pre.current.querySelectorAll` to an array.
I created a repo with a reproducible scenario and more information about the issue and the proposed fix: https://github.com/arthurdenner/docusaurus-twoslash-bug

fix(docusaurus-preset): fix text collection for copy button

---

examples/docusaurus/docs/intro.md
examples/docusaurus/docusaurus.config.js
examples/docusaurus/package.json
examples/docusaurus/yarn.lock
packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css
packages/remark-shiki-twoslash/src/index.ts
packages/shiki-twoslash/README.md
packages/shiki-twoslash/src/index.ts

This PR does
- Adds an `ignoreCodeblocksWithCodefenceMeta` option which will ignore transforming certain code blocks (only intended to work with remark)
For example,
```json5
{
"theme": "nord",
"ignoreCodeblocksWithCodefenceMeta": ["live"] // ```jsx live - will be ignored
}
```
This feature won't do anything until we remove the `MDXComponents` file in docusaurus preset. The canary release of Docusaurus is now working fine without the `MDXComponents` but not having the file breaks twoslash in all other older versions of Docusaurus. I'd like to wait for (at least) a major release to remove the file. #72 will have to wait for that.
To see the results, simply update all docusaurus plugins in the `example/docusaurus` to `canary` and remove the `MDXComponents` file in the preset (locally for …
```

Ignore option

---

.changeset/kind-gifts-agree.md
packages/markdown-it-shiki-twoslash/src/index.ts
packages/markdown-it-shiki-twoslash/test/markdown-it.test.ts

markdown-it's parser produces code blocks with a trailing newline,
seemingly in conformance with the
[commonmark spec](https://spec.commonmark.org/0.12/#indented-code-blocks).
shiki-twoslash should avoid treating this line as contentful, as doing
so results in generated html with a "line" for that newline, adding an
extra newline to the user-provided code block. To avoid this unexpected
behavior, simply remove the trailing newline before twoslash-shiki
processing.
Closes #90

Remove trailing newline in code blocks before twoslash processing

---

.changeset/tidy-beans-shout.md
packages/eleventy-plugin-shiki-twoslash/index.js

This PR fixed the same issue fixed in PR: https://github.com/shikijs/twoslash/commit/d34ecb58ea391c7e81fc554b2515f9811ba2a1af for markdown-it.
Credits: @ayazhafiz

Remove trailing newline

---

.changeset/unlucky-keys-sing.md
packages/shiki-twoslash/src/index.ts

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Comment

shiki-twoslash: fix HTML comment syntax

---

packages/remark-shiki-twoslash/src/caching.ts

Use correct cache path after splitting based on `node_modules`

---

.changeset/eight-drinks-march.md
packages/remark-shiki-twoslash/src/caching.ts

When installed under Yarn w/ PnP, packages are mounted as readonly zip archives. As a result, the remark caching logic that currently tries to locate the node_modules from `__dirname` results in the artifacts being written into the (read-only) archive, thus failing.
This diff fixes that by checking whether the current process operates under PnP mode, and using the PnP API in that case (which is a sounder way to get the project root anyway).

Uses the PnP API to derive a safe cache folder

---

.changeset/great-adults-sort.md
packages/remark-shiki-twoslash/src/caching.ts

I made a typo in #115: `process.env.pnp` should be `process.versions.pnp`.
Tested locally using `yarn link` (weirdly, building the package using `pnpm pack` didn't work ... I got [this error](https://user-images.githubusercontent.com/1037931/135528526-8254fb0e-14e1-41bb-8e9f-076b2fb3ac1a.png), without stacktraces; doesn't seem related to my change, though).

Fixes typo

---

site/pages/index.tsx

~~Adding value 1 char at a time :wink: ~~
I've added in the tweak about being explicit that twoslash works with JS/TS and not all languages.
https://github.com/shikijs/twoslash/issues/119

Fix typo / be explicit about TypeScript / JavaScript

---

site/components/docs/Queries.mdx

There's a missing `"` in the first code snippet that causes a failure:
https://shikijs.github.io/twoslash/playground?#code/MYewdgzgLgBAFgSxgXhgIgBIFMA2ORoBQoksAthAOYrxIDU6ANDAO4gBOOAJoQPS8xBMAHoB+IA

Fix error in playground example

---

.changeset/cool-trains-build.md
packages/remark-shiki-twoslash/src/index.ts

It would be nice to be able to do this:
```js
import remarkShikiTwoslash, { type Options } from "remark-shiki-twoslash";
```
Instead of this:
```js
import remarkShikiTwoslash from "remark-shiki-twoslash";
import { type UserConfigSettings as Options } from "shiki-twoslash";
```
I named the export `Options` to match the convention of recent releases of remark/rehype packages:
- https://github.com/rehypejs/rehype-autolink-headings#types
- https://github.com/remarkjs/remark-gfm#types
- https://github.com/rehypejs/rehype-raw#types

Export `Options` type for remark plugin

---

.changeset/mighty-maps-kneel.md
packages/remark-shiki-twoslash/src/caching.ts

The cache calculation was using the wrong variable name, sometimes causing incorrect results.

Fixes typo in the symbol name

---

.changeset/fifty-rabbits-mix.md
packages/remark-shiki-twoslash/src/exceptionMessageDOM.ts

Hi there!
This PR resolves an issue I was running into when using `remark-shiki-twoslash` with `@mdx-js/loader`. 
When using a twoslash code block with a TypeScript generic that has a type error, `@mdx-js/loader` throws an exception when attempting to render the Twoslash failure message block.
Here's the code block I was trying to use:
````
```ts twoslash
type MyPick<T, K> = {
[Key in K]: T[Key]
}
```
````
This is the exception message: ``Error: Cannot turn `t, ` into a JSX identifier``. If I rename `T` to `R`, it becomes ``Error: Cannot turn `r,` into a JSX identifier``, and so on. It seems like `remark` reads `<` as the start of an element.
I was able to track this down to the fact that the code isn't escaped in `setupNodeForTwoslashException`. Escaping the code allows the failure to …

Escape code within Twoslash failure messages

---

.changeset/green-colts-battle.md
packages/remark-shiki-twoslash/src/exceptionMessageDOM.ts

When error titles/descriptions/recommendations have angle brackets in them, they don't display correctly because they are not escaped. In my case, the `error.recommendation` property had angle brackets in it because the message contained generics.
This PR escapes the text in those positions, so they display correctly.

Escape HTML in error message/recommendation

---

packages/twoslash-cli/README.md

The example command uses wrong option.

Fix cli docs

---

.changeset/lazy-poets-complain.md
packages/eleventy-plugin-shiki-twoslash/package.json
packages/markdown-it-shiki-twoslash/package.json
packages/remark-shiki-twoslash/package.json
packages/shiki-twoslash/package.json
pnpm-lock.yaml
site/package.json

This PR upgrades the upstream dependency of `shiki` to `0.10.1`.
I was unable to find a changelog of what was changed in `shiki@0.10.0` over `0.9.15`  outside of this list of commits:
https://github.com/shikijs/shiki/compare/1d5379138d706239c6bf9c337f655d40ad0bd92e...v0.10.0
And looking through each of the commits, I couldn't see an obvious breaking API that would require major refactor work.
Closes #155

feat: upgrade shiki to 0.10.1

---

packages/docusaurus-preset-shiki-twoslash/package.json
packages/eleventy-plugin-shiki-twoslash/package.json
packages/hexo-shiki-twoslash/package.json
packages/markdown-it-shiki-twoslash/package.json

Without this I hit workspace issues when running `pnpm boostrap`.
```
╭─[00:00]: captbaritone at moffo in ~/projects/twoslash on branch*
╰─➤ pnpm bootstrap
> shiki-twoslash-monorepo@ bootstrap /Users/captbaritone/projects/twoslash
> pnpm recursive run --workspace-concurrency 1 build  && md-magic
Scope: all 10 workspace projects
> shiki-twoslash-monorepo@ build /Users/captbaritone/projects/twoslash
> pnpm run build -r && md-magic
Scope: all 10 workspace projects
> shiki-twoslash@3.1.0 build /Users/captbaritone/projects/twoslash/packages/shiki-twoslash
> tsdx build
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
@rollup/plugin-replace: 'preventAssignment' …
```

Use pnpm rather than npx for bootstrapping

---

.changeset/slow-poets-speak.md
packages/remark-shiki-twoslash/package.json
packages/shiki-twoslash/package.json
pnpm-lock.yaml
site/package.json

- Due to the `ReturnType` use [here](https://github.com/shikijs/twoslash/blob/main/packages/shiki-twoslash/src/utils.ts#L1-L3), the generated types for `shiki-twoslash` include a reference to `fenceparser`, which should then be in the `dependencies` listing.
- Similarly, the `import 'unist'` [here](https://github.com/arcanis/twoslash/blob/patch-2/packages/remark-shiki-twoslash/src/index.ts#L1) doesn't work out-of-the-box since `@types/unist` isn't listed in the dependencies (of note, the `unist` package doesn't exist, only `@types/unist` does).
- Since the intent is probably to use whatever TS version the consumer uses, `typescript` should be a peer dependency rather than a regular dependency (otherwise there's a chance some hoisting mess will happen, especially if the user happens to use …

Fixes dependencies

---

.changeset/spotty-hairs-clean.md
packages/shiki-twoslash/src/renderers/twoslash.ts

Fixes closing tag for completion result.
---
Got the following error while using with Vitepress:
```
Element is missing end tag
```
With this code:
````markdown
```ts twoslash
// @noErrors
console.e
//       ^|
```
````
And inspecting the generated code (below), lead me to the syntax error.
```html
<pre class="shiki vitesse-dark twoslash lsp" style="background-color: #121212; color: #dbd7ca"><div class="language-id">ts</div><div class='code-container'><code><div class='line'><span style="color: #B8A965"><data-lsp lsp='var console: Console' >console</data-lsp></span><span style="color: #858585">.</span><span style="color: #B8A965"><data-lsp lsp='any' >e</data-lsp></span></div><div class='meta-line'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class='inline-completions'><ul …
```

fix: completion result closing tag
